### ISSUE TITLE
Improved android design

### ISSUE THREAD

**Issue by hamsternik** [heutagogy/HeutagogyMobileApp#17]
Actually, we got a good design keeps the [Android standarts](https://developer.android.com/design/index.html) for our application, which you can find [here](mockups/android).
So, here you find which screens have been implemented:

- [ ] Login screen
- [ ] List of Articles screen
- [ ] Navigation Drawer screen 

<img width="360" alt="1" src="https://cloud.githubusercontent.com/assets/4441804/23623322/4ed4eef8-02aa-11e7-82ea-4c49a14195a1.png">
<img width="360" alt="2" src="https://cloud.githubusercontent.com/assets/4441804/23623321/4ed4f84e-02aa-11e7-97b9-6bd6cce63788.png">
<img width="360" alt="3" src="https://cloud.githubusercontent.com/assets/4441804/23623325/4ed726dc-02aa-11e7-9a60-dc99a9533636.png">
<img width="360" alt="4" src="https://cloud.githubusercontent.com/assets/4441804/23623324/4ed63c68-02aa-11e7-80a1-f55041a4c458.png">
<img width="360" alt="5" src="https://cloud.githubusercontent.com/assets/4441804/23623326/4ed900c4-02aa-11e7-9a13-137f9b4998c5.png">
<img width="360" alt="6" src="https://cloud.githubusercontent.com/assets/4441804/23623323/4ed522ce-02aa-11e7-9989-111dd3b6c255.png">
<img width="360" alt="7" src="https://cloud.githubusercontent.com/assets/4441804/23623328/4ef7a5f6-02aa-11e7-9339-fc5a48598ad2.png">

![8](https://cloud.githubusercontent.com/assets/4441804/23623403/9abcf6da-02aa-11e7-8343-3e63deefb633.png)

**Comment by drets** [comment]
@hamsternik, thank you for creating it.
